---
sidebar: sidebar 
keywords: Cyber vault, cybervault, cyber-vault, data protection, security, ransomware, ONTAP, hardening 
permalink: cyber-vault/ontap-cyber-vault-interop.html 
summary: 网络保险库互操作性 
---
= 网络保险库互操作性
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP硬件和软件可用于创建网络保险库配置。



== ONTAP硬件建议

所有ONTAP统一物理阵列均可用于网络保险库实施。

* FAS混合存储提供了最具成本效益的解决方案。
* AFF C 系列提供最高效的功耗和密度。
* AFF A 系列是性能最高的平台，提供最佳的 RTO。随着我们最新AFF A 系列的发布，该平台将提供最佳的存储效率，同时不影响性能。




== ONTAP软件建议

从ONTAP 9.14.1 开始，您可以在SnapMirror关系的SnapMirror策略中为特定SnapMirror标签指定保留期，以便从源卷到目标卷复制的 Snapshot 副本保留规则中指定的保留期。如果未指定保留期，则使用目标卷的默认保留期。

从ONTAP 9.13.1 开始，您可以通过创建FlexClone并将 snaplock-type 选项设置为“non-snaplock”并在执行卷克隆创建操作时将 Snapshot 副本指定为“parent-snapshot”，从而立即恢复SnapLockSnapLock库关系的目标 SnapLock 卷上的锁定 Snapshot 副本。详细了解link:https://docs.netapp.com/us-en/ontap/volumes/create-flexclone-task.html?q=volume+clone["创建具有SnapLock类型的FlexClone卷"^] 。



== MetroCluster 配置

对于MetroCluster配置，您应该注意以下事项：

* 您只能在同步源 SVM 之间创建SnapVault关系，而不能在同步源 SVM 和同步目标 SVM 之间创建 SnapVault 关系。
* 您可以创建从同步源 SVM 上的卷到数据服务 SVM 的SnapVault关系。
* 您可以创建从数据服务 SVM 上的卷到同步源 SVM 上的 DP 卷的SnapVault关系。

