---
sidebar: sidebar 
permalink: cyber-vault/ontap-cyber-vault-ps-consider.html 
keywords: Cyber vault, powershell, script, configuration, validation, hardening 
summary: 这是用于配置、强化和验证基于ONTAP的网络保险库的NetApp ONTAP解决方案 
---
= 其他注意事项
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在设计和部署基于ONTAP 的网络保险库时，还需要考虑其他因素。



== 容量大小考虑因素

ONTAP Cyber Vault 目标卷所需的磁盘空间量取决于多种因素，其中最重要的是源卷中数据的变化率。目标卷上的备份计划和快照计划都会影响目标卷上的磁盘使用情况，并且源卷上的变化率可能不会保持恒定。最好提供额外的存储容量缓冲区，以满足未来最终用户或应用程序行为变化的需求。

在ONTAP中确定 1 个月保留关系的大小需要根据多种因素计算存储需求，包括主数据集的大小、数据变化率（每日变化率）以及重复数据删除和压缩节省（如果适用）。

以下是分步方法：

第一步是了解使用网络保险库保护的源卷的大小。这是最初复制到网络保险库目的地的基本数据量。接下来，估计数据集的每日变化率。这是每天变化的数据百分比。充分了解数据的动态性至关重要。

例如：

* 主数据集大小 = 5TB
* 每日变化率=5%（0.05）
* 重复数据删除和压缩效率 = 50% (0.50)


现在，让我们来看一下计算过程：

* 计算每日数据变化率：
+
`Changed data per day = 5000 * 5% = 250GB`

* 计算30天的总变化数据：
+
`Total changed data in 30 days = 250 GB * 30 = 7.5TB`

* 计算所需的总存储量：
+
`TOTAL = 5TB + 7.5TB = 12.5TB`

* 应用重复数据删除和压缩节省：
+
`EFFECTIVE = 12.5TB * 50% = 6.25TB`



*存储需求摘要*

* 如果没有效率：存储 30 天的网络保险库数据将需要 *12.5TB*。
* 效率为 50%：重复数据删除和压缩后需要 *6.25TB* 的存储空间。



NOTE: 快照副本可能会因元数据而产生额外的开销，但这通常很小。


NOTE: 如果每天进行多次备份，则根据每天拍摄的 Snapshot 副本数量调整计算。


NOTE: 考虑数据随时间的增长，以确保规模适合未来。



== 对主要/源的性能影响

由于数据传输是一种拉取操作，因此对主存储性能的影响可能因工作负载、数据量和备份频率而异。然而，由于数据传输旨在将数据保护和备份任务卸载到网络保险库存储系统，因此对主系统的整体性能影响通常是适度且可控的。在初始关系设置和第一次完整备份期间，大量数据从主系统传输到网络保险库系统（ SnapLock Compliance卷）。这会导致主系统的网络流量和 I/O 负载增加。初始完整备份完成后， ONTAP只需要跟踪和传输自上次备份以来发生变化的块。与初始复制相比，这会导致 I/O 负载小得多。增量更新效率高，对主存储性能的影响最小。保险库进程在后台运行，从而减少了干扰主系统生产工作负载的可能性。

* 确保存储系统有足够的资源（CPU、内存和 IOP）来处理额外的负载，从而减轻性能影响。

