---
sidebar: sidebar 
permalink: automation/getting-started.html 
summary: NetApp解决方案自动化使客户能够自动部署、配置和执行许多常见的基础设施和应用程序任务。 
keywords: netapp, awx, tower, ansible tower, solutions, automation, ansible, getting, started 
---
= NetApp解决方案自动化入门
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp解决方案自动化为NetApp解决方案所使用的许多常见任务提供了简单性和可重复性。

在运行任何解决方案自动化之前，必须配置环境以确定如何执行自动化。可以选择从命令行或通过 AWX 或 Tower 等工具运行自动化。

以下部分将概述为每个指定环境配置环境所需的步骤。

.在 RHEL / CentOS 上为 CLI 部署设置 Ansible 控制节点
[%collapsible%open]
====
. Ansible 控制节点的要求：
+
.. 安装了以下软件包的 RHEL/CentOS 机器：
+
... Python3
... Pip3
... Ansible（版本高于 2.10.0）
... Git






如果您有一台新的 RHEL/CentOS 机器，但没有安装上述要求，请按照以下步骤将该机器设置为 Ansible 控制节点：

. 为 RHEL-8/RHEL-7 启用 Ansible 存储库
+
.. 对于 RHEL-8（以 root 身份运行以下命令）
+
[source, cli]
----
subscription-manager repos --enable ansible-2.9-for-rhel-8-x86_64-rpms
----
.. 对于 RHEL-7（以 root 身份运行以下命令）
+
[source, cli]
----
subscription-manager repos --enable rhel-7-server-ansible-2.9-rpms
----


. 将以下内容粘贴到终端中
+
[source, cli]
----
sudo yum -y install python3 >> install.log
sudo yum -y install python3-pip >> install.log
python3 -W ignore -m pip --disable-pip-version-check install ansible >> install.log
sudo yum -y install git >> install.log
----


====
.在 Ubuntu / Debian 上为 CLI 部署设置 Ansible 控制节点
[%collapsible%open]
====
. Ansible 控制节点的要求：
+
.. 安装了以下软件包的 Ubuntu/Debian 机器：
+
... Python3
... Pip3
... Ansible（版本高于 2.10.0）
... Git






如果您有一台新的 Ubuntu/Debian 机器，但没有安装上述要求，请按照以下步骤将该机器设置为 Ansible 控制节点：

. 将下面的内容粘贴到终端中
+
[source, cli]
----
sudo apt-get -y install python3 >> outputlog.txt
sudo apt-get -y install python3-pip >> outputlog.txt
python3 -W ignore -m pip --disable-pip-version-check install ansible >> outputlog.txt
sudo apt-get -y install git >> outputlog.txt
----


====
.为 Tower/AWX 部署设置 Ansible Tower 或 AWX
[%collapsible%open]
====
本节介绍在 AWX/Ansible Tower 中配置参数所需的步骤，为使用NetApp自动化解决方案准备环境。

. 配置库存。
+
.. 导航至资源 → 库存 → 添加，然后单击添加库存。
.. 提供姓名和组织详细信息，然后单击“保存”。
.. 在库存页面中，单击刚刚创建的库存资源。
.. 如果有任何库存变量，请将其粘贴到变量字段中。
.. 转到“组”子菜单并单击“添加”。
.. 提供组的名称，复制组变量（如有必要），然后单击“保存”。
.. 单击创建的组，转到“主机”子菜单，然后单击“添加新主机”。
.. 提供主机的主机名和 IP 地址，粘贴主机变量（如有必要），然后单击“保存”。


. 创建凭证类型。对于涉及ONTAP、Element、VMware 或任何其他基于 HTTPS 的传输连接的解决方案，您必须配置凭证类型以匹配用户名和密码条目。
+
.. 导航到管理 → 凭证类型并单击添加。
.. 提供名称和描述。
.. 将以下内容粘贴到输入配置中：




[listing]
----
fields:
- id: username
type: string
label: Username
- id: password
type: string
label: Password
secret: true
- id: vsadmin_password
type: string
label: vsadmin_password
secret: true
----
. 将以下内容粘贴到注入器配置中：


[listing]
----
extra_vars:
password: '{{ password }}'
username: '{{ username }}'
vsadmin_password: '{{ vsadmin_password }}'
----
. 配置凭据。
+
.. 导航到资源 → 凭证并单击添加。
.. 输入姓名和组织详细信息。
.. 选择正确的凭证类型；如果您打算使用标准 SSH 登录，请选择 Machine 类型，或者选择您创建的自定义凭证类型。
.. 输入其他相应详细信息并单击“保存”。


. 配置项目。
+
.. 导航到资源 → 项目并单击添加。
.. 输入姓名和组织详细信息。
.. 选择 Git 作为源代码控制凭证类型。
.. 粘贴与特定解决方案对应的源代码控制 URL（或 git 克隆 URL）。
.. 或者，如果 Git URL 受到访问控制，请在源代码控制凭证中创建并附加相应的凭证。
.. 单击“Save”。


. 配置作业模板。
+
.. 导航到资源 → 模板 → 添加，然后单击添加作业模板。
.. 输入名称和描述。
.. 选择作业类型；运行根据剧本配置系统，检查执行剧本的试运行而不实际配置系统。
.. 为剧本选择相应的库存、项目和凭证。
.. 选择您想要作为作业模板的一部分运行的剧本。
.. 通常变量是在运行时粘贴的。因此，为了在运行时获得填充变量的提示，请确保勾选与变量字段对应的启动时提示复选框。
.. 根据需要提供任何其他详细信息，然后单击“保存”。


. 启动作业模板。
+
.. 导航至资源 → 模板。
.. 单击所需的模板，然后单击启动。
.. 如果启动时出现提示，请填写任何变量，然后再次单击“启动”。




====
欲了解更多信息，请访问link:https://netapp.io/2018/10/08/getting-started-with-netapp-and-ansible-install-ansible/["NetApp解决方案自动化和 Ansible 入门"]

要请求自动化，请填写link:https://github.com/NetAppDocs/netapp-solutions/issues/new?body=%5BRequest%20Automation%5D%0d%0a%0d%0aSolution%20Name:%20%0d%0aRequest%20Title:%20%0d%0aDescription:%0d%0aSuggestions:&title=Request%20Automation%20-%20["自动化请求表"]。
